### ISSUE TITLE
Boardwalk indexer for Commons metadata

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/administration#13]

**Comment by mikebaumann** [comment]
Moved to BD2KGenomics/dss-azul-indexer#19

**Comment by mikebaumann** [comment]
Demo:
Show indexer ingesting TOPMed 12k metadata and creating an index in ElasticSearch

**Comment by caaespin** [comment]
- Safe harbor is just to edit the old school [metadata indexer ](https://github.com/BD2KGenomics/dcc-metadata-indexer/) to index new columns on the TSV and stick them in the right place in the metadata.json

- Once the metadata is available on the HCA DSS, write the config and test against using the HCA DSS eventing. Switch to [dss-azul-indexer](https://github.com/BD2KGenomics/dss-azul-indexer)

**Comment by mikebaumann** [comment]
Moving to BD2K repos.
