### ISSUE TITLE
DOS read access to HCA DSS mock metadata, public access data

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/administration#27]

**Comment by david4096** [comment]
https://github.com/DataBiosphere/dos-dss-lambda includes a service that is pointed at:

```
DSS_URL = "https://commons-dss.ucsc-cgp-dev.org/v1"
```

It minimally presents data access to each of the primary keys. Open issues: secondary metadata is not present in the DOS messages, ListDataObjects is not implemented, and paging doesn't work properly.

**Comment by david4096** [comment]
Added the ability to retrieve file metadata.

**Comment by david4096** [comment]
Quick update, still need to provide access to new "data by reference" feature.

https://docs.google.com/document/d/15tiZXtZQZyDbkdoHESosSKfdlBxCssJXGDFSImeKu0U/edit#

**Comment by david4096** [comment]
Data by reference feature is handled now. The commons DSS data is available in a DOS instance.
