### ISSUE TITLE
Load Spinnaker/Redwood and HCA DSS with TOPMed 12k large files by reference with minimal, real metadata

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/administration#28]

**Comment by briandoconnor** [comment]
Walt, Brian, Jonathon  -

Yes, it's okay for all 29 fields x 12,000+ rows of the metadata itself to be publicly available.  The first 11 columns come verbatim from dbGaP data that is (or was once) publicly available, if you know where to look for it.  The rest of the information, although not all of it is publicly available elsewhere (sequencing_center, receipt_group, read_length, file_size_Gb, md5 checksums) is not sensitive information in any way.  It could not be used to identify a particular research study subject.

What IS sensitive is the sequence data at those path names, similarly genotype data when that is posted in the future.

Question for Goncalo -- if this is going to become a public face of the TOPMed project, do we want to dress up the data in any way ?

                                                -  thanks  -  tom blackwell  -
