### ISSUE TITLE
DOS objectives for Face to Face

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/administration#70]
Steinberg is the lead for this working group for the face to face

https://docs.google.com/document/d/1FVZgFWDABkqeT0sglLpn-t7Ve689crFbw-8j9moVWEE/edit#heading=h.hv9qx7actzph

* we need objectives for the meeting
* We need an agenda for the working time
* We need a proposal of time

**Comment by david4096** [comment]
Alright I added some objectives to the document. Would you like us to prepare agendas in separate documents?
